# Generated by Django 4.2 on 2023-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfoodrecipe',
            name='food_recipe',
        ),
        migrations.AddField(
            model_name='clientfoodrecipe',
            name='food_recipe',
            field=models.ManyToManyField(to='catalog.foodrecipe'),
        ),
    ]
