# Generated by Django 4.2 on 2023-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_clientfoodrecipe_food_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='food_yield',
            field=models.CharField(default='1 unidade', max_length=30),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='time_prepare',
            field=models.IntegerField(default=60),
        ),
    ]
