# Generated by Django 4.2 on 2023-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_foodrecipe_food_yield_foodrecipe_time_prepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='food_yield',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
