# Generated by Django 4.2 on 2023-04-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_created_at_client_updated_at'),
        ('catalog', '0006_alter_foodrecipe_food_yield_alter_foodrecipe_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('foods', models.ManyToManyField(to='catalog.food')),
            ],
        ),
    ]
