# Generated by Django 4.2 on 2023-04-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_clientfood_clientnotfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type_food',
        ),
    ]
