# Generated by Django 4.2 on 2023-04-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_food_type_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeFood',
        ),
    ]
