# Generated by Django 4.2 on 2023-04-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_typefood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientFoodRecipe',
        ),
    ]
