# Generated by Django 4.2 on 2023-04-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
