# Generated by Django 4.2 on 2023-04-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
